name: Rust

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-channel: ['stable', 'nightly']
        rust-target: [
            'armv7-linux-androideabi',
            'aarch64-linux-android',
            'i686-linux-android',
            'x86_64-linux-android',
        ]

    steps:
    - uses: actions/checkout@v2

    - name: Download NDK
      run: |
        curl -LO https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
        unzip android-ndk-r20-linux-x86_64.zip -d $GITHUB_WORKSPACE
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-package: jre # Runtime new enough for android toolchain
        java-version: '13'

    - name: Installing Rust ${{ matrix.rust-channel }} w/ ${{ matrix.rust-target }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-channel }}
        target: ${{ matrix.rust-target }}
        override: true

    - name: Run tests
      run: |
        cargo test --manifest-path oboe-sys/Cargo.toml --features test
        cargo test --manifest-path oboe/Cargo.toml --features rustdoc --doc
        # cargo test -p oboe
    - name: Install cargo-apk
      run:
        cargo install cargo-apk

    - name: Check compiling on target ${{ matrix.rust-target }}
      run: |
        export NDK_HOME="$GITHUB_WORKSPACE/android-ndk-r20"
        export CC="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
        export AR="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
        cargo check -p oboe --target ${{ matrix.rust-target }}
        # cargo apk build -p oboe-demo --target ${{ matrix.rust-target }} --examples
